AWSTemplateFormatVersion: "2010-09-09"
Description: EventBridge schedule to run Lambda (acrJiraTokenExipryCheckLambda) every 3 minutes with full-permission IAM role

Resources:
  # IAM Role with full permissions
  FullAccessAutomationRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: AcrJiraTokenExpiryAccessAutomationRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
                - events.amazonaws.com
                - scheduler.amazonaws.com
            Action: sts:AssumeRole
      Path: "/"
      Policies:
        - PolicyName: FullAccessIAMEventBridgeLambdaSNSLogsS3Secrets
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - iam:*
                  - events:*
                  - scheduler:*
                  - lambda:*
                  - sns:*
                  - logs:*
                  - s3:*
                  - secretsmanager:*
                  - cloudwatch:*     # ✅ Added CloudWatch full access
                Resource: "*"

  # EventBridge Scheduler to invoke Lambda
  LambdaSchedule:
    Type: AWS::Scheduler::Schedule
    Properties:
      Name: AcrJiraLambdaScheduleEvery3Minutes   # Schedule name
      FlexibleTimeWindow:
        Mode: OFF  # Run exactly on schedule without delays
      ScheduleExpression: rate(3 minutes)   # Runs every 3 minutes
      Target:
        Arn: arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function/acrJiraTokenExipryCheckLambda
        RoleArn: !GetAtt FullAccessAutomationRole.Arn

Outputs:
  ScheduleName:
    Description: Name of the EventBridge schedule
    Value: !Ref LambdaSchedule
  LambdaFunctionArn:
    Description: ARN of the Lambda being triggered
    Value: arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function/acrJiraTokenExipryCheckLambda
  RoleName:
    Description: Name of the IAM Role created
    Value: !Ref FullAccessAutomationRole
  RoleArn:
    Description: ARN of the IAM Role created
    Value: !GetAtt FullAccessAutomationRole.Arn