AWSTemplateFormatVersion: "2010-09-09"
Description: EventBridge schedule to run Lambda (acrJiraTokenExipryCheckLambda) every 3 minutes

Resources:
  LambdaSchedule:
    Type: AWS::Scheduler::Schedule
    Properties:
      Name: AcrJiraLambdaScheduleEvery3Minutes   # You can change this name if needed
      FlexibleTimeWindow:
        Mode: OFF  # Run exactly on schedule without delays
      ScheduleExpression: rate(3 minutes)   # Runs every 3 minutes
      Target:
        Arn: arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function/acrJiraTokenExipryCheckLambda
        # 👉 Hardcoded Lambda function name
        RoleArn: arn:aws:iam::833376745199:role/AcrJiraTokenExpiryAccessAutomationRole
        # 👉 Hardcoded IAM role ARN

  # Policy to allow EventBridge Scheduler role to invoke Lambda
  SchedulerInvokeLambdaPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: AllowSchedulerInvokeAcrJiraLambda
      Roles:
        - AcrJiraTokenExpiryAccessAutomationRole   # 👉 Role name only, not ARN
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action: lambda:InvokeFunction
            Resource: arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function/acrJiraTokenExipryCheckLambda

Outputs:
  ScheduleName:
    Description: Name of the EventBridge schedule
    Value: !Ref LambdaSchedule
  LambdaFunctionArn:
    Description: ARN of the Lambda being triggered
    Value: arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function/acrJiraTokenExipryCheckLambda