AWSTemplateFormatVersion: "2010-09-09"
Description: EventBridge schedule to run Lambda (acrJiraTokenExipryCheckLambda) every 3 minutes

Resources:
  LambdaSchedule:
    Type: AWS::Scheduler::Schedule
    Properties:
      Name: AcrJiraLambdaScheduleEvery3Minutes
      FlexibleTimeWindow:
        Mode: OFF
      ScheduleExpression: rate(3 minutes)
      Target:
        Arn: arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function/acrJiraTokenExipryCheckLambda
        RoleArn: arn:aws:iam::123456789012:role/AcrJiraTokenExpiryAccessAutomationRole 
        # ——— Replace the above ARN with the RoleArn output from Template 1

Outputs:
  ScheduleName:
    Description: Name of the EventBridge schedule
    Value: !Ref LambdaSchedule
  LambdaFunctionArn:
    Description: ARN of the Lambda being triggered
    Value: arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function/acrJiraTokenExipryCheckLambda
