apiVersion: v1
kind: Namespace
metadata:
  name: dayatest
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-stress
  namespace: dayatest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu-stress
  template:
    metadata:
      labels:
        app: ubuntu-stress
    spec:
      containers:
      - name: ubuntu
        image: ubuntu:22.04
        command: ["/bin/bash", "-c"]
        args:
          - |
            apt-get update && apt-get install -y stress-ng curl;
            while true; do
              echo "CPU spike for 2 minutes...";
              stress-ng --cpu 2 --timeout 120s --metrics-brief;
              echo "Spike finished, sleeping 2 minutes...";
              sleep 120;
            done
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "2000m"
            memory: "512Mi"
        startupProbe:
          exec:
            command: ["bash", "-c", "which stress-ng || echo not-yet"]
          failureThreshold: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command: ["bash", "-c", "which stress-ng"]
          initialDelaySeconds: 5
          periodSeconds: 10
          failureThreshold: 5
        livenessProbe:
          exec:
            command: ["bash", "-c", "pgrep stress-ng || exit 1"]
          initialDelaySeconds: 60
          periodSeconds: 30
          failureThreshold: 3